'use strict';

/**
 * Generates valid, openable test attachment files at a precise target size.
 *
 * Supported formats:
 *   .pdf  — valid PDF built manually with comment-line padding (no extra deps)
 *   .pptx — minimal valid OOXML/ZIP presentation with a binary padding file inside
 *   other — raw binary blob (correct size, not format-specific)
 */

// ─── CRC32 (needed for ZIP) ───────────────────────────────────────────────────
const _CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let j = 0; j < 8; j++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
    t[i] = c;
  }
  return t;
})();

function crc32(buf) {
  let c = 0xFFFFFFFF;
  for (let i = 0; i < buf.length; i++) c = (c >>> 8) ^ _CRC_TABLE[(c ^ buf[i]) & 0xFF];
  return (c ^ 0xFFFFFFFF) >>> 0;
}

// ─── Minimal ZIP builder (STORED, no compression) ────────────────────────────
function buildZip(files) {
  const locals = [];
  const centralEntries = [];
  let offset = 0;

  for (const { name, data } of files) {
    const nameBuf = Buffer.from(name, 'utf8');
    const crc     = crc32(data);
    const size    = data.length;

    const local = Buffer.alloc(30 + nameBuf.length);
    local.writeUInt32LE(0x04034B50, 0);
    local.writeUInt16LE(20,          4);
    local.writeUInt16LE(0,           6);
    local.writeUInt16LE(0,           8);   // STORED
    local.writeUInt16LE(0,          10);
    local.writeUInt16LE(0,          12);
    local.writeUInt32LE(crc,        14);
    local.writeUInt32LE(size,       18);
    local.writeUInt32LE(size,       22);
    local.writeUInt16LE(nameBuf.length, 26);
    local.writeUInt16LE(0,          28);
    nameBuf.copy(local, 30);
    locals.push(local, data);

    const cd = Buffer.alloc(46 + nameBuf.length);
    cd.writeUInt32LE(0x02014B50, 0);
    cd.writeUInt16LE(20,          4);
    cd.writeUInt16LE(20,          6);
    cd.writeUInt16LE(0,           8);
    cd.writeUInt16LE(0,          10);
    cd.writeUInt16LE(0,          12);
    cd.writeUInt16LE(0,          14);
    cd.writeUInt32LE(crc,        16);
    cd.writeUInt32LE(size,       20);
    cd.writeUInt32LE(size,       24);
    cd.writeUInt16LE(nameBuf.length, 28);
    cd.writeUInt16LE(0,          30);
    cd.writeUInt16LE(0,          32);
    cd.writeUInt16LE(0,          34);
    cd.writeUInt16LE(0,          36);
    cd.writeUInt32LE(0,          38);
    cd.writeUInt32LE(offset,     42);
    nameBuf.copy(cd, 46);
    centralEntries.push(cd);

    offset += local.length + data.length;
  }

  const cdBuf    = Buffer.concat(centralEntries);
  const eocd     = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054B50, 0);
  eocd.writeUInt16LE(0,           4);
  eocd.writeUInt16LE(0,           6);
  eocd.writeUInt16LE(files.length, 8);
  eocd.writeUInt16LE(files.length, 10);
  eocd.writeUInt32LE(cdBuf.length, 12);
  eocd.writeUInt32LE(offset,       16);
  eocd.writeUInt16LE(0,            20);

  return Buffer.concat([...locals, cdBuf, eocd]);
}

// ─── PDF generator ────────────────────────────────────────────────────────────
function generatePdfBuffer(targetBytes) {
  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n',
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n',
    '3 0 obj\n<< /Type /Page /MediaBox [0 0 612 792] /Parent 2 0 R\n   /Resources << /Font << /F1 4 0 R >> >>\n   /Contents 5 0 R >>\nendobj\n',
    '4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n',
  ];
  const pageText = [
    'BT',
    '/F1 20 Tf',
    '50 740 Td (CloudFuze QA Migration - Large Attachment Test) Tj',
    '0 -30 Td /F1 12 Tf (This file is used to validate large attachment migration.) Tj',
    '0 -20 Td (Generated by CloudFuze QA Agent.) Tj',
    'ET',
  ].join('\n');
  objects.push(`5 0 obj\n<< /Length ${pageText.length} >>\nstream\n${pageText}\nendstream\nendobj\n`);

  const baseContent = objects.join('');
  const header      = '%PDF-1.4\n%\xe2\xe3\xcf\xd3\n';
  const trailerTemplate = (xrefOff, offsets) => [
    'xref',
    `0 ${offsets.length + 1}`,
    '0000000000 65535 f ',
    ...offsets.map(o => String(o).padStart(10, '0') + ' 00000 n '),
    'trailer',
    `<< /Size ${offsets.length + 1} /Root 1 0 R >>`,
    'startxref',
    String(xrefOff),
    '%%EOF',
    '',
  ].join('\n');

  // Build base PDF (no padding) so we know the exact base size
  const baseOffsets = [];
  let basePos = header.length;
  for (const obj of objects) { baseOffsets.push(basePos); basePos += obj.length; }
  const baseTrailer = trailerTemplate(basePos, baseOffsets);
  const baseSize    = header.length + baseContent.length + baseTrailer.length;

  // Padding goes between header and objects as % comment lines.
  // The padding shifts all object offsets, so we iterate to converge.
  const paddingLine = '% CloudFuze QA Agent padding data\n';
  let padLen = Math.max(0, targetBytes - baseSize);

  let full = '';
  for (let iter = 0; iter < 6; iter++) {
    const rep     = Math.floor(padLen / paddingLine.length);
    const rem     = padLen % paddingLine.length;
    // Remainder line: '% ' + spaces to fill, terminated with \n
    const padding = paddingLine.repeat(rep) + (rem > 2 ? '% ' + ' '.repeat(rem - 3) + '\n' : rem > 0 ? ' '.repeat(rem) : '');
    const actualPadLen = Buffer.byteLength(padding);

    const offsets = [];
    let pos = header.length + actualPadLen;
    for (const obj of objects) { offsets.push(pos); pos += obj.length; }
    const trailer = trailerTemplate(pos, offsets);
    full = header + padding + baseContent + trailer;

    const diff = targetBytes - Buffer.byteLength(full);
    if (diff === 0) break;
    padLen = Math.max(0, actualPadLen + diff);
  }

  const buf = Buffer.from(full);
  // %%EOF must always be intact — never slice. If slightly over, append nothing.
  // If slightly under, pad with harmless whitespace AFTER %%EOF (readers tolerate trailing spaces).
  if (buf.length >= targetBytes) return buf;
  return Buffer.concat([buf, Buffer.alloc(targetBytes - buf.length, 0x20)]);
}

// ─── PPTX generator (minimal valid OOXML inside a ZIP) ───────────────────────
function generatePptxBuffer(targetBytes) {
  const f = (name, xml) => ({ name, data: Buffer.from(xml.trim(), 'utf8') });

  const baseFiles = [
    f('[Content_Types].xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml"  ContentType="application/xml"/>
  <Default Extension="bin"  ContentType="application/octet-stream"/>
  <Override PartName="/ppt/presentation.xml"
    ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>
  <Override PartName="/ppt/slides/slide1.xml"
    ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>
  <Override PartName="/ppt/slideLayouts/slideLayout1.xml"
    ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/>
  <Override PartName="/ppt/slideMasters/slideMaster1.xml"
    ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/>
  <Override PartName="/ppt/theme/theme1.xml"
    ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>
</Types>`),
    f('_rels/.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1"
    Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"
    Target="ppt/presentation.xml"/>
</Relationships>`),
    f('ppt/presentation.xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentation xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"
                xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
                xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst>
  <p:sldIdLst><p:sldId id="256" r:id="rId2"/></p:sldIdLst>
  <p:sldSz cx="9144000" cy="6858000"/>
  <p:notesSz cx="6858000" cy="9144000"/>
</p:presentation>`),
    f('ppt/_rels/presentation.xml.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1"
    Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster"
    Target="slideMasters/slideMaster1.xml"/>
  <Relationship Id="rId2"
    Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide"
    Target="slides/slide1.xml"/>
</Relationships>`),
    f('ppt/slides/slide1.xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"
       xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
       xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
      <p:sp>
        <p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr><a:spLocks noGrp="1"/></p:cNvSpPr><p:nvPr><p:ph type="title"/></p:nvPr></p:nvSpPr>
        <p:spPr/>
        <p:txBody><a:bodyPr/><a:lstStyle/>
          <a:p><a:r><a:t>CloudFuze QA - Large Attachment Migration Test</a:t></a:r></a:p>
        </p:txBody>
      </p:sp>
    </p:spTree>
  </p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sld>`),
    f('ppt/slides/_rels/slide1.xml.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1"
    Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout"
    Target="../slideLayouts/slideLayout1.xml"/>
</Relationships>`),
    f('ppt/slideLayouts/slideLayout1.xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sldLayout xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"
             xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
             xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
             type="blank" preserve="1">
  <p:cSld name="Blank">
    <p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
    <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
    </p:spTree>
  </p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sldLayout>`),
    f('ppt/slideLayouts/_rels/slideLayout1.xml.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1"
    Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster"
    Target="../slideMasters/slideMaster1.xml"/>
</Relationships>`),
    f('ppt/slideMasters/slideMaster1.xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sldMaster xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"
             xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
             xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <p:cSld>
    <p:bg><p:bgRef idx="1001"><a:schemeClr clr="bg1"/></p:bgRef></p:bg>
    <p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
    <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
    </p:spTree>
  </p:cSld>
  <p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2"
            accent1="accent1" accent2="accent2" accent3="accent3"
            accent4="accent4" accent5="accent5" accent6="accent6"
            hlink="hlink" folHlink="folHlink"/>
  <p:sldLayoutIdLst><p:sldLayoutId id="2147483649" r:id="rId1"/></p:sldLayoutIdLst>
  <p:txStyles>
    <p:titleStyle><a:lstStyle/></p:titleStyle>
    <p:bodyStyle><a:lstStyle/></p:bodyStyle>
    <p:otherStyle><a:lstStyle/></p:otherStyle>
  </p:txStyles>
</p:sldMaster>`),
    f('ppt/slideMasters/_rels/slideMaster1.xml.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1"
    Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout"
    Target="../slideLayouts/slideLayout1.xml"/>
  <Relationship Id="rId2"
    Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme"
    Target="../theme/theme1.xml"/>
</Relationships>`),
    f('ppt/theme/theme1.xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Office Theme">
  <a:themeElements>
    <a:clrScheme name="Office">
      <a:dk1><a:sysClr lastClr="000000" val="windowText"/></a:dk1>
      <a:lt1><a:sysClr lastClr="ffffff" val="window"/></a:lt1>
      <a:dk2><a:srgbClr val="44546A"/></a:dk2>
      <a:lt2><a:srgbClr val="E7E6E6"/></a:lt2>
      <a:accent1><a:srgbClr val="4472C4"/></a:accent1>
      <a:accent2><a:srgbClr val="ED7D31"/></a:accent2>
      <a:accent3><a:srgbClr val="A9D18E"/></a:accent3>
      <a:accent4><a:srgbClr val="FF0000"/></a:accent4>
      <a:accent5><a:srgbClr val="FFC000"/></a:accent5>
      <a:accent6><a:srgbClr val="70AD47"/></a:accent6>
      <a:hlink><a:srgbClr val="0563C1"/></a:hlink>
      <a:folHlink><a:srgbClr val="954F72"/></a:folHlink>
    </a:clrScheme>
    <a:fontScheme name="Office">
      <a:majorFont><a:latin typeface="Calibri Light"/><a:ea typeface=""/><a:cs typeface=""/></a:majorFont>
      <a:minorFont><a:latin typeface="Calibri"/><a:ea typeface=""/><a:cs typeface=""/></a:minorFont>
    </a:fontScheme>
    <a:fmtScheme name="Office">
      <a:fillStyleLst><a:solidFill><a:schemeClr clr="phClr"/></a:solidFill></a:fillStyleLst>
      <a:lnStyleLst><a:ln w="6350" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:schemeClr clr="phClr"/></a:solidFill><a:prstDash val="solid"/></a:ln></a:lnStyleLst>
      <a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst>
      <a:bgFillStyleLst><a:solidFill><a:schemeClr clr="phClr"/></a:solidFill></a:bgFillStyleLst>
    </a:fmtScheme>
  </a:themeElements>
</a:theme>`),
  ];

  // Build without padding to measure base size
  const baseZip      = buildZip(baseFiles);
  const padFileName  = 'ppt/media/data.bin';
  // overhead for one extra ZIP entry: local header + central dir entry (both include filename length)
  const entryOverhead = (30 + padFileName.length) + (46 + padFileName.length);
  const paddingSize  = Math.max(0, targetBytes - baseZip.length - entryOverhead);

  const allFiles = [...baseFiles, { name: padFileName, data: Buffer.alloc(paddingSize, 0x42) }];
  return buildZip(allFiles);
}

// ─── Public API ───────────────────────────────────────────────────────────────
/**
 * Returns a Buffer with valid file content matching the target size.
 * @param {string} fileName  e.g. "qa-attachment-26mb.pptx"
 * @param {number} sizeMB    target size in megabytes
 */
function generateTestFileBuffer(fileName, sizeMB) {
  const targetBytes = sizeMB * 1024 * 1024;
  const ext = (fileName.split('.').pop() || '').toLowerCase();
  if (ext === 'pdf')  return generatePdfBuffer(targetBytes);
  if (ext === 'pptx') return generatePptxBuffer(targetBytes);
  // Generic binary fallback (txt, docx, xlsx, csv, png, etc.)
  const buf = Buffer.alloc(targetBytes, 0x41);
  Buffer.from(`CloudFuze QA Migration Test - ${fileName}\n`).copy(buf, 0);
  return buf;
}

module.exports = { generateTestFileBuffer };
