google.service-account.key-path=service-account.json
google.admin.email=YOUR_GOOGLE_ADMIN_EMAIL

# Microsoft Teams (Azure AD App Registration)
microsoft.tenant-id=YOUR_TENANT_ID
microsoft.client-id=YOUR_CLIENT_ID
microsoft.client-secret=YOUR_CLIENT_SECRET
microsoft.admin.email=YOUR_ADMIN_EMAIL

server.port=8080
spring.mvc.async.request-timeout=600000
spring.jackson.serialization.write-dates-as-timestamps=false

logging.level.com.cloudfuze=INFO
logging.pattern.console=%d{HH:mm:ss} [%level] %msg%n
